baseURL = "https://cps-lab-saga.github.io/image-processing-widget/"
languageCode = 'en-us'
title = 'Image Processing Widget'
theme = 'PaperMod'

[params]
description = "GUI to explore OpenCV image processing functions."
author = "WL Yeoh"

[module]
[[module.mounts]]
source = "../README.md"
target = "content/_index.md"

[[module.mounts]]
source = '../screenshots'
target = 'static/screenshots'