import numpy as np

mask = [
    np.array(
        [[0, 0, 0],
         [0, 1, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 1, 1],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 1],
         [0, 1, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 1, 0],
         [0, 1, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[1, 0, 0],
         [0, 1, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 2, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [1, 1, 1],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 1],
         [0, 1, 0],
         [1, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 1, 0],
         [0, 1, 0],
         [0, 1, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[1, 0, 0],
         [0, 1, 0],
         [0, 0, 1]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 1],
         [1, 1, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 1, 0],
         [0, 1, 0],
         [1, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[1, 0, 0],
         [0, 1, 0],
         [0, 1, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [1, 1, 0],
         [0, 0, 1]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 1, 1],
         [1, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 1],
         [0, 1, 0],
         [0, 1, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 1, 0],
         [0, 1, 0],
         [0, 0, 1]],
        dtype=np.uint8,
    ),
    np.array(
        [[1, 0, 0],
         [0, 1, 1],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 1, 0],
         [1, 1, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[1, 0, 0],
         [0, 1, 0],
         [1, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [1, 1, 0],
         [0, 1, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 1, 0],
         [1, 0, 1]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 1, 1],
         [0, 1, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 1],
         [0, 1, 0],
         [0, 0, 1]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 1, 0],
         [0, 1, 1],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[1, 0, 1],
         [0, 1, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 2, 1],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 1],
         [0, 2, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 1, 0],
         [0, 2, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[1, 0, 0],
         [0, 2, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [1, 2, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 2, 0],
         [1, 0, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 2, 0],
         [0, 1, 0]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 2, 0],
         [0, 0, 1]],
        dtype=np.uint8,
    ),
    np.array(
        [[0, 0, 0],
         [0, 3, 0],
         [0, 0, 0]],
        dtype=np.uint8,
    ),
]
